pipeline {
    agent any
    tools {
        maven "maven3"
        jdk "OracleJDK8"
    }

    environment {
        imagename = "172.31.62.128:8082/vprofile"
        nexusCredential = "nexus"
    }
    
    stages {

    stage("Build App Image") {
                steps {
                    script {
                dockerImage = docker.build( imagename + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
                    }
                }
    }
 
    stage('Upload App Image to Nexus') {
            steps{
                script {
                echo 'Pushing image to docker hosted rerpository on Nexus'

                withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'PSW', usernameVariable: 'USER')]){
                    sh "echo ${PSW} | docker login -u ${USER} --password-stdin 172.31.62.128:8082"
                    }
                docker.withRegistry( '', nexusCredential ) {
                    dockerImage.push("$BUILD_NUMBER")
                }
                }
                }
            }
            }
}
