pipeline {
    agent any
    tools {
        maven "maven3"
        jdk "OracleJDK8"
    }
    
    environment {
        SNAP_REPO = 'vprofile-snapshot'
	NEXUS_USER = 'admin'
	NEXUS_PASS = 'umer'
	RELEASE_REPO = 'vprofile-release'
	CENTRAL_REPO = 'vpro-maven-central'
	NEXUSIP = '172.31.87.206'
	NEXUSPORT = '8081'
	NEXUS_GRP_REPO = 'vpro-maven-group'
    NEXUS_LOGIN = 'nexuslogin'
    SONARSERVER = 'sonarserver'
    SONARSCANNER = 'sonarscanner'
    registry = "docker.io/20216627/vprofile"
    registryCredential = 'dockerhubcreds'
    dockerImage = ''
    }

    stages {


   
    stage("Build App Image") {
                steps {
                    script {
                        dockerImage = docker.build( registry + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
                    }
                    }
                }
 
    }
}
